//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeodeticCoordinateConversion.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class zh_cn {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal zh_cn() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeodeticCoordinateConversion.Resources.zh_cn", typeof(zh_cn).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 放弃更改.
        /// </summary>
        internal static string AbortChange {
            get {
                return ResourceManager.GetString("AbortChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关于.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 向当前表添加一条记录.
        /// </summary>
        internal static string AddNewRecordToTable {
            get {
                return ResourceManager.GetString("AddNewRecordToTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加新行.
        /// </summary>
        internal static string AddNewRow {
            get {
                return ResourceManager.GetString("AddNewRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 外观.
        /// </summary>
        internal static string Appearance {
            get {
                return ResourceManager.GetString("Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 大地坐标转换实习程序.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 传入了未知的参数。.
        /// </summary>
        internal static string ArgumentUnknown {
            get {
                return ResourceManager.GetString("ArgumentUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 绑定事件失败。.
        /// </summary>
        internal static string BindEventFailed {
            get {
                return ResourceManager.GetString("BindEventFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 纬度应介于 {0} - {1} 间，当前值为 {2}。.
        /// </summary>
        internal static string BiotitudeOutOfRange {
            get {
                return ResourceManager.GetString("BiotitudeOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已计算数据颜色.
        /// </summary>
        internal static string CalculatedColor {
            get {
                return ResourceManager.GetString("CalculatedColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将应用数据保存到数据库时，清空目标数据库记录.
        /// </summary>
        internal static string ClearExistingRecordData2DB {
            get {
                return ResourceManager.GetString("ClearExistingRecordData2DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将应用数据保存到文件时，清空目标文件记录.
        /// </summary>
        internal static string ClearExistingRecordData2File {
            get {
                return ResourceManager.GetString("ClearExistingRecordData2File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将数据库导出到文件时，清空目标文件记录.
        /// </summary>
        internal static string ClearExistingRecordDB2File {
            get {
                return ResourceManager.GetString("ClearExistingRecordDB2File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将文件数据导入到数据库时，清空目标数据库记录.
        /// </summary>
        internal static string ClearExistingRecordFile2DB {
            get {
                return ResourceManager.GetString("ClearExistingRecordFile2DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ，.
        /// </summary>
        internal static string Comma {
            get {
                return ResourceManager.GetString("Comma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 从3度带转换到6度带失败。.
        /// </summary>
        internal static string Convert3To6Failed {
            get {
                return ResourceManager.GetString("Convert3To6Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 从6度带转换到3度带失败。.
        /// </summary>
        internal static string Convert6To3Failed {
            get {
                return ResourceManager.GetString("Convert6To3Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 从字符串读取度分秒信息失败。.
        /// </summary>
        internal static string ConvertFromStringFailed {
            get {
                return ResourceManager.GetString("ConvertFromStringFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上一次转换操作出现问题，请检查后重试。.
        /// </summary>
        internal static string ConvertOperationFailed {
            get {
                return ResourceManager.GetString("ConvertOperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 完成，共有 {1} 条记录，计算了 {2} 条记录，成功 {3} 条，失败 {4} 条。.
        /// </summary>
        internal static string ConvertResult {
            get {
                return ResourceManager.GetString("ConvertResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将度分秒信息转换为字符串失败。.
        /// </summary>
        internal static string ConvertToStringFailed {
            get {
                return ResourceManager.GetString("ConvertToStringFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 坐标转换.
        /// </summary>
        internal static string CoordConvert {
            get {
                return ResourceManager.GetString("CoordConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 坐标转换对象包含的地理经纬度对象的GUID。.
        /// </summary>
        internal static string CoordConvertBL {
            get {
                return ResourceManager.GetString("CoordConvertBL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 坐标转换对象包含的高斯坐标对象的GUID。.
        /// </summary>
        internal static string CoordConvertGauss {
            get {
                return ResourceManager.GetString("CoordConvertGauss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 坐标转换对象初始化失败。.
        /// </summary>
        internal static string CoordConvertInitializeError {
            get {
                return ResourceManager.GetString("CoordConvertInitializeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将坐标转换对象保存到XML结构失败。.
        /// </summary>
        internal static string CoordConvertSaveToXmlFailed {
            get {
                return ResourceManager.GetString("CoordConvertSaveToXmlFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 坐标转换对象的GUID。.
        /// </summary>
        internal static string CoordConvertUID {
            get {
                return ResourceManager.GetString("CoordConvertUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正确记录颜色.
        /// </summary>
        internal static string CorrectColor {
            get {
                return ResourceManager.GetString("CorrectColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据.
        /// </summary>
        internal static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据文件管理对象初始化失败。.
        /// </summary>
        internal static string DataFileInitializeError {
            get {
                return ResourceManager.GetString("DataFileInitializeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据文件名.
        /// </summary>
        internal static string DataFileName {
            get {
                return ResourceManager.GetString("DataFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前选定的选项卡不包含计算用数据框。.
        /// </summary>
        internal static string DataGridViewNotExist {
            get {
                return ResourceManager.GetString("DataGridViewNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 从{0}加载了 {1} 条{2}记录。.
        /// </summary>
        internal static string DataLoaded {
            get {
                return ResourceManager.GetString("DataLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已将 {0} 条{1}记录保存到{2}。.
        /// </summary>
        internal static string DataSaved {
            get {
                return ResourceManager.GetString("DataSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 对象是否已计算。.
        /// </summary>
        internal static string DataStatusCalculated {
            get {
                return ResourceManager.GetString("DataStatusCalculated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 对象是否为脏数据。.
        /// </summary>
        internal static string DataStatusDirty {
            get {
                return ResourceManager.GetString("DataStatusDirty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 对象是否有计算错误。.
        /// </summary>
        internal static string DataStatusError {
            get {
                return ResourceManager.GetString("DataStatusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 对象是否选中。.
        /// </summary>
        internal static string DataStatusSelected {
            get {
                return ResourceManager.GetString("DataStatusSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据表.
        /// </summary>
        internal static string DataTable {
            get {
                return ResourceManager.GetString("DataTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据库管理对象初始化失败。.
        /// </summary>
        internal static string DBInitializeError {
            get {
                return ResourceManager.GetString("DBInitializeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据库文件名.
        /// </summary>
        internal static string DBName {
            get {
                return ResourceManager.GetString("DBName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成功将数据库 {0} 中 {1} 条坐标转换记录和 {2}  条换带记录导出到文件 {3}。.
        /// </summary>
        internal static string DBSavedToFile {
            get {
                return ResourceManager.GetString("DBSavedToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据查看.
        /// </summary>
        internal static string DBTab {
            get {
                return ResourceManager.GetString("DBTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 夜深了.
        /// </summary>
        internal static string DeepNight {
            get {
                return ResourceManager.GetString("DeepNight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 默认单元格颜色.
        /// </summary>
        internal static string DefaultCellColor {
            get {
                return ResourceManager.GetString("DefaultCellColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 默认椭球.
        /// </summary>
        internal static string DefaultEllipse {
            get {
                return ResourceManager.GetString("DefaultEllipse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加新记录时的默认椭球.
        /// </summary>
        internal static string DefaultEllipseAddingRow {
            get {
                return ResourceManager.GetString("DefaultEllipseAddingRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 默认分带.
        /// </summary>
        internal static string DefaultZoneType {
            get {
                return ResourceManager.GetString("DefaultZoneType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加新记录时的默认分带.
        /// </summary>
        internal static string DefaultZoneTypeAddingRow {
            get {
                return ResourceManager.GetString("DefaultZoneTypeAddingRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 度应介于 {0} - {1} 间，当前值为 {2}。.
        /// </summary>
        internal static string DegreeOutOfRange {
            get {
                return ResourceManager.GetString("DegreeOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除选中行.
        /// </summary>
        internal static string DeleteRow {
            get {
                return ResourceManager.GetString("DeleteRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除选中的记录.
        /// </summary>
        internal static string DeleteSelectedRecord {
            get {
                return ResourceManager.GetString("DeleteSelectedRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 指定的文件夹不存在。.
        /// </summary>
        internal static string DirectoryNotFound {
            get {
                return ResourceManager.GetString("DirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 脏数据颜色.
        /// </summary>
        internal static string DirtyColor {
            get {
                return ResourceManager.GetString("DirtyColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 度分秒对象初始化失败。.
        /// </summary>
        internal static string DMSInitializeError {
            get {
                return ResourceManager.GetString("DMSInitializeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未初始化度分秒对象。.
        /// </summary>
        internal static string DMSNull {
            get {
                return ResourceManager.GetString("DMSNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将度分秒对象保存到XML结构失败。.
        /// </summary>
        internal static string DMSSaveToXmlFailed {
            get {
                return ResourceManager.GetString("DMSSaveToXmlFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未设置椭球类型。.
        /// </summary>
        internal static string EllipseNotSet {
            get {
                return ResourceManager.GetString("EllipseNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未初始化椭球对象。.
        /// </summary>
        internal static string EllipseNull {
            get {
                return ResourceManager.GetString("EllipseNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未知的椭球类型。.
        /// </summary>
        internal static string EllipseUnknown {
            get {
                return ResourceManager.GetString("EllipseUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据框为空。.
        /// </summary>
        internal static string EmptyDataGridView {
            get {
                return ResourceManager.GetString("EmptyDataGridView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 英语.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 错误记录颜色.
        /// </summary>
        internal static string ErrorColor {
            get {
                return ResourceManager.GetString("ErrorColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 指定数据文件出错。.
        /// </summary>
        internal static string ErrSpecifyingDataFile {
            get {
                return ResourceManager.GetString("ErrSpecifyingDataFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 指定的文件不存在。.
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成功将文件 {0} 中 {1} 条坐标转换记录和 {2}  条换带记录导入到数据库 {3}。.
        /// </summary>
        internal static string FileSavedToDB {
            get {
                return ResourceManager.GetString("FileSavedToDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 该功能暂未实现。.
        /// </summary>
        internal static string FunctionNotImplemented {
            get {
                return ResourceManager.GetString("FunctionNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 高斯坐标.
        /// </summary>
        internal static string GaussCoord {
            get {
                return ResourceManager.GetString("GaussCoord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 高斯坐标的椭球类型。.
        /// </summary>
        internal static string GaussCoordEllipseType {
            get {
                return ResourceManager.GetString("GaussCoordEllipseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 高斯坐标对象初始化失败。.
        /// </summary>
        internal static string GaussCoordInitializeError {
            get {
                return ResourceManager.GetString("GaussCoordInitializeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将高斯坐标对象保存到XML结构失败。.
        /// </summary>
        internal static string GaussCoordSaveToXmlFailed {
            get {
                return ResourceManager.GetString("GaussCoordSaveToXmlFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 高斯坐标对象的GUID。.
        /// </summary>
        internal static string GaussCoordUID {
            get {
                return ResourceManager.GetString("GaussCoordUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 带内X坐标。.
        /// </summary>
        internal static string GaussCoordX {
            get {
                return ResourceManager.GetString("GaussCoordX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 带内Y坐标。.
        /// </summary>
        internal static string GaussCoordY {
            get {
                return ResourceManager.GetString("GaussCoordY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 高斯坐标带号。.
        /// </summary>
        internal static string GaussCoordZone {
            get {
                return ResourceManager.GetString("GaussCoordZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 高斯坐标的分带类型。.
        /// </summary>
        internal static string GaussCoordZoneType {
            get {
                return ResourceManager.GetString("GaussCoordZoneType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 高斯正算失败。.
        /// </summary>
        internal static string GaussDirectFailed {
            get {
                return ResourceManager.GetString("GaussDirectFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未初始化高斯坐标对象。.
        /// </summary>
        internal static string GaussNull {
            get {
                return ResourceManager.GetString("GaussNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 高斯反算失败。.
        /// </summary>
        internal static string GaussReverseFailed {
            get {
                return ResourceManager.GetString("GaussReverseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 高斯坐标转换到地理经纬度失败。.
        /// </summary>
        internal static string GaussToGEOBLFailed {
            get {
                return ResourceManager.GetString("GaussToGEOBLFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通用.
        /// </summary>
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 地理经纬度.
        /// </summary>
        internal static string GEOBL {
            get {
                return ResourceManager.GetString("GEOBL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 表示纬度的字符串。.
        /// </summary>
        internal static string GEOBLB {
            get {
                return ResourceManager.GetString("GEOBLB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 地理经纬度的椭球类型。.
        /// </summary>
        internal static string GEOBLEllipseType {
            get {
                return ResourceManager.GetString("GEOBLEllipseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 地理经纬度对象初始化失败。.
        /// </summary>
        internal static string GEOBLInitializeError {
            get {
                return ResourceManager.GetString("GEOBLInitializeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 表示经度的字符串。.
        /// </summary>
        internal static string GEOBLL {
            get {
                return ResourceManager.GetString("GEOBLL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未初始化地理经纬度对象。.
        /// </summary>
        internal static string GEOBLNull {
            get {
                return ResourceManager.GetString("GEOBLNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将地理经纬度对象保存到XML结构失败。.
        /// </summary>
        internal static string GEOBLSaveToXmlFailed {
            get {
                return ResourceManager.GetString("GEOBLSaveToXmlFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 地理经纬度转换到高斯坐标失败。.
        /// </summary>
        internal static string GEOBLToGaussFailed {
            get {
                return ResourceManager.GetString("GEOBLToGaussFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 地理经纬度对象的GUID。.
        /// </summary>
        internal static string GEOBLUID {
            get {
                return ResourceManager.GetString("GEOBLUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 地理经纬度的分带类型。.
        /// </summary>
        internal static string GEOBLZoneType {
            get {
                return ResourceManager.GetString("GEOBLZoneType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 椭球对象初始化失败。.
        /// </summary>
        internal static string GEOEllipseInitializeError {
            get {
                return ResourceManager.GetString("GEOEllipseInitializeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将椭球对象保存到XML结构失败。.
        /// </summary>
        internal static string GEOEllipseSaveToXmlFailed {
            get {
                return ResourceManager.GetString("GEOEllipseSaveToXmlFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 计算中央经线失败。.
        /// </summary>
        internal static string GetCenterFailed {
            get {
                return ResourceManager.GetString("GetCenterFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下午好.
        /// </summary>
        internal static string GoodAfternoon {
            get {
                return ResourceManager.GetString("GoodAfternoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 晚上好.
        /// </summary>
        internal static string GoodEvening {
            get {
                return ResourceManager.GetString("GoodEvening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上午好.
        /// </summary>
        internal static string GoodMorning {
            get {
                return ResourceManager.GetString("GoodMorning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中午好.
        /// </summary>
        internal static string GoodNoon {
            get {
                return ResourceManager.GetString("GoodNoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 哈喽.
        /// </summary>
        internal static string Halo {
            get {
                return ResourceManager.GetString("Halo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 你好.
        /// </summary>
        internal static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 反选.
        /// </summary>
        internal static string InvertSelect {
            get {
                return ResourceManager.GetString("InvertSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 语言.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 从数据库加载记录.
        /// </summary>
        internal static string LoadDB {
            get {
                return ResourceManager.GetString("LoadDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 从文件导入数据库.
        /// </summary>
        internal static string LoadDBFromFile {
            get {
                return ResourceManager.GetString("LoadDBFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 从文件加载记录.
        /// </summary>
        internal static string LoadFile {
            get {
                return ResourceManager.GetString("LoadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 经度应介于 {0} - {1} 间，当前值为 {2}。.
        /// </summary>
        internal static string LongitudeOutOfRange {
            get {
                return ResourceManager.GetString("LongitudeOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分应介于 {0} - {1} 间，当前值为 {2}。.
        /// </summary>
        internal static string MinuteOutOfRange {
            get {
                return ResourceManager.GetString("MinuteOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新的一天开始了.
        /// </summary>
        internal static string NewDay {
            get {
                return ResourceManager.GetString("NewDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 夜猫子.
        /// </summary>
        internal static string NightOwl {
            get {
                return ResourceManager.GetString("NightOwl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 少女祈祷中....
        /// </summary>
        internal static string NowLoading {
            get {
                return ResourceManager.GetString("NowLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开工作文件夹.
        /// </summary>
        internal static string OpenWorkFolder {
            get {
                return ResourceManager.GetString("OpenWorkFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户取消了操作。.
        /// </summary>
        internal static string OperationCanceledByUser {
            get {
                return ResourceManager.GetString("OperationCanceledByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 。.
        /// </summary>
        internal static string PeriodComma {
            get {
                return ResourceManager.GetString("PeriodComma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 项目Github地址.
        /// </summary>
        internal static string ProjectAddressOnGithub {
            get {
                return ResourceManager.GetString("ProjectAddressOnGithub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 从数据库重新加载当前表.
        /// </summary>
        internal static string ReloadTable {
            get {
                return ResourceManager.GetString("ReloadTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 恢复默认值.
        /// </summary>
        internal static string ResetDefault {
            get {
                return ResourceManager.GetString("ResetDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将所有设置恢复到默认值（需要重启）.
        /// </summary>
        internal static string ResetDefaultRequireStart {
            get {
                return ResourceManager.GetString("ResetDefaultRequireStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加了1条新的记录。.
        /// </summary>
        internal static string RowAdded {
            get {
                return ResourceManager.GetString("RowAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除了 {0} 条记录。.
        /// </summary>
        internal static string RowDeleted {
            get {
                return ResourceManager.GetString("RowDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用于初始化对象的两个高斯坐标拥有同样的分带类型。.
        /// </summary>
        internal static string SameZoneType {
            get {
                return ResourceManager.GetString("SameZoneType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存更改（需要重启）.
        /// </summary>
        internal static string SaveBtnRequireRestart {
            get {
                return ResourceManager.GetString("SaveBtnRequireRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将记录保存到数据库.
        /// </summary>
        internal static string SaveDB {
            get {
                return ResourceManager.GetString("SaveDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将数据库导出到文件.
        /// </summary>
        internal static string SaveDBToFile {
            get {
                return ResourceManager.GetString("SaveDBToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将记录保存到文件.
        /// </summary>
        internal static string SaveFile {
            get {
                return ResourceManager.GetString("SaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存对选中表的更改.
        /// </summary>
        internal static string SaveTableChanges {
            get {
                return ResourceManager.GetString("SaveTableChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 秒应介于 {0} - {1} 间，当前值为 {2}。.
        /// </summary>
        internal static string SecondOutOfRange {
            get {
                return ResourceManager.GetString("SecondOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全选.
        /// </summary>
        internal static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选中记录颜色.
        /// </summary>
        internal static string SelectedColor {
            get {
                return ResourceManager.GetString("SelectedColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全不选.
        /// </summary>
        internal static string SelectNone {
            get {
                return ResourceManager.GetString("SelectNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择工作文件夹.
        /// </summary>
        internal static string SelectWorkFolder {
            get {
                return ResourceManager.GetString("SelectWorkFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置应用的语言.
        /// </summary>
        internal static string SetAppLanguage {
            get {
                return ResourceManager.GetString("SetAppLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置中央经线失败。.
        /// </summary>
        internal static string SetCenterFailed {
            get {
                return ResourceManager.GetString("SetCenterFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置数据库存放目录失败。.
        /// </summary>
        internal static string SetDBPathFailed {
            get {
                return ResourceManager.GetString("SetDBPathFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置数据文件存放目录失败。.
        /// </summary>
        internal static string SetDocPathFailed {
            get {
                return ResourceManager.GetString("SetDocPathFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置椭球类型失败。.
        /// </summary>
        internal static string SetEllipseTypeFailed {
            get {
                return ResourceManager.GetString("SetEllipseTypeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 大地坐标转换设置.
        /// </summary>
        internal static string SettingTitle {
            get {
                return ResourceManager.GetString("SettingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置高斯坐标带号失败。.
        /// </summary>
        internal static string SetZoneFailed {
            get {
                return ResourceManager.GetString("SetZoneFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 简体中文.
        /// </summary>
        internal static string SimplifiedChinese {
            get {
                return ResourceManager.GetString("SimplifiedChinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 坐标转换转移至换带后，自动切换标签页.
        /// </summary>
        internal static string SwitchAfterGaussTransfer {
            get {
                return ResourceManager.GetString("SwitchAfterGaussTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在数据库 {0} 中找到 {1} 张表。.
        /// </summary>
        internal static string TableListLoaded {
            get {
                return ResourceManager.GetString("TableListLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 表中有 {1} 条记录。.
        /// </summary>
        internal static string TableRecordCount {
            get {
                return ResourceManager.GetString("TableRecordCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已从数据库 {0} 重载表 {1}。.
        /// </summary>
        internal static string TableReloaded {
            get {
                return ResourceManager.GetString("TableReloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 高斯坐标转移到换带.
        /// </summary>
        internal static string TransferToZoneConvert {
            get {
                return ResourceManager.GetString("TransferToZoneConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工作文件夹.
        /// </summary>
        internal static string WorkFolder {
            get {
                return ResourceManager.GetString("WorkFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 字符串小数点位置错误。.
        /// </summary>
        internal static string WrongDigitPosition {
            get {
                return ResourceManager.GetString("WrongDigitPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3度分带带号应介于 {0} - {1} 间，当前值为 {2}。.
        /// </summary>
        internal static string Zone3OutOfRange {
            get {
                return ResourceManager.GetString("Zone3OutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6度分带带号应介于 {0} - {1} 间，当前值为 {2}。.
        /// </summary>
        internal static string Zone6OutOfRange {
            get {
                return ResourceManager.GetString("Zone6OutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 换带计算.
        /// </summary>
        internal static string ZoneConvert {
            get {
                return ResourceManager.GetString("ZoneConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 换带操作失败。.
        /// </summary>
        internal static string ZoneConvertFailed {
            get {
                return ResourceManager.GetString("ZoneConvertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 换带对象包含的高斯3°带坐标对象的GUID。.
        /// </summary>
        internal static string ZoneConvertGauss3 {
            get {
                return ResourceManager.GetString("ZoneConvertGauss3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 换带对象包含的高斯6°带坐标对象的GUID。.
        /// </summary>
        internal static string ZoneConvertGauss6 {
            get {
                return ResourceManager.GetString("ZoneConvertGauss6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 换带初始化失败。.
        /// </summary>
        internal static string ZoneConvertInitializeError {
            get {
                return ResourceManager.GetString("ZoneConvertInitializeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将换带对象保存到XML结构失败。.
        /// </summary>
        internal static string ZoneConvertSaveToXmlFailed {
            get {
                return ResourceManager.GetString("ZoneConvertSaveToXmlFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 换带对象的GUID。.
        /// </summary>
        internal static string ZoneConvertUID {
            get {
                return ResourceManager.GetString("ZoneConvertUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未设置分带类型。.
        /// </summary>
        internal static string ZoneTypeNotSet {
            get {
                return ResourceManager.GetString("ZoneTypeNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未知的分带类型。.
        /// </summary>
        internal static string ZoneTypeUnknown {
            get {
                return ResourceManager.GetString("ZoneTypeUnknown", resourceCulture);
            }
        }
    }
}
