//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeodeticCoordinateConversion.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class zh_cn {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal zh_cn() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeodeticCoordinateConversion.Resources.zh_cn", typeof(zh_cn).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 放弃更改.
        /// </summary>
        internal static string AbortChange {
            get {
                return ResourceManager.GetString("AbortChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 外观.
        /// </summary>
        internal static string Appearance {
            get {
                return ResourceManager.GetString("Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已计算数据颜色.
        /// </summary>
        internal static string CalculatedColor {
            get {
                return ResourceManager.GetString("CalculatedColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将应用数据保存到数据库时，清空目标数据库记录.
        /// </summary>
        internal static string ClearExistingRecordData2DB {
            get {
                return ResourceManager.GetString("ClearExistingRecordData2DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将应用数据保存到文件时，清空目标文件记录.
        /// </summary>
        internal static string ClearExistingRecordData2File {
            get {
                return ResourceManager.GetString("ClearExistingRecordData2File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将数据库导出到文件时，清空目标文件记录.
        /// </summary>
        internal static string ClearExistingRecordDB2File {
            get {
                return ResourceManager.GetString("ClearExistingRecordDB2File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将文件数据导入到数据库时，清空目标数据库记录.
        /// </summary>
        internal static string ClearExistingRecordFile2DB {
            get {
                return ResourceManager.GetString("ClearExistingRecordFile2DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正确记录颜色.
        /// </summary>
        internal static string CorrectColor {
            get {
                return ResourceManager.GetString("CorrectColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据.
        /// </summary>
        internal static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据文件名.
        /// </summary>
        internal static string DataFileName {
            get {
                return ResourceManager.GetString("DataFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据库文件名.
        /// </summary>
        internal static string DBName {
            get {
                return ResourceManager.GetString("DBName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 默认单元格颜色.
        /// </summary>
        internal static string DefaultCellColor {
            get {
                return ResourceManager.GetString("DefaultCellColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 默认椭球.
        /// </summary>
        internal static string DefaultEllipse {
            get {
                return ResourceManager.GetString("DefaultEllipse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加新记录时的默认椭球.
        /// </summary>
        internal static string DefaultEllipseAddingRow {
            get {
                return ResourceManager.GetString("DefaultEllipseAddingRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 默认分带.
        /// </summary>
        internal static string DefaultZoneType {
            get {
                return ResourceManager.GetString("DefaultZoneType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加新记录时的默认分带.
        /// </summary>
        internal static string DefaultZoneTypeAddingRow {
            get {
                return ResourceManager.GetString("DefaultZoneTypeAddingRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 脏数据颜色.
        /// </summary>
        internal static string DirtyColor {
            get {
                return ResourceManager.GetString("DirtyColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 英语.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 错误记录颜色.
        /// </summary>
        internal static string ErrorColor {
            get {
                return ResourceManager.GetString("ErrorColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通用.
        /// </summary>
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 语言.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开工作文件夹.
        /// </summary>
        internal static string OpenWorkFolder {
            get {
                return ResourceManager.GetString("OpenWorkFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 恢复默认值.
        /// </summary>
        internal static string ResetDefault {
            get {
                return ResourceManager.GetString("ResetDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将所有设置恢复到默认值（需要重启）.
        /// </summary>
        internal static string ResetDefaultRequireStart {
            get {
                return ResourceManager.GetString("ResetDefaultRequireStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存更改（需要重启）.
        /// </summary>
        internal static string SaveBtnRequireRestart {
            get {
                return ResourceManager.GetString("SaveBtnRequireRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选中记录颜色.
        /// </summary>
        internal static string SelectedColor {
            get {
                return ResourceManager.GetString("SelectedColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择工作文件夹.
        /// </summary>
        internal static string SelectWorkFolder {
            get {
                return ResourceManager.GetString("SelectWorkFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置应用的语言.
        /// </summary>
        internal static string SetAppLanguage {
            get {
                return ResourceManager.GetString("SetAppLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 大地坐标转换设置.
        /// </summary>
        internal static string SettingTitle {
            get {
                return ResourceManager.GetString("SettingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 简体中文.
        /// </summary>
        internal static string SimplifiedChinese {
            get {
                return ResourceManager.GetString("SimplifiedChinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 坐标转换转移至换带后，自动切换标签页.
        /// </summary>
        internal static string SwitchAfterGaussTransfer {
            get {
                return ResourceManager.GetString("SwitchAfterGaussTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工作文件夹.
        /// </summary>
        internal static string WorkFolder {
            get {
                return ResourceManager.GetString("WorkFolder", resourceCulture);
            }
        }
    }
}
